### ISSUE TITLE
[FR] Add ability to read the html from file

### ISSUE THREAD

**Issue by NightMachinery** [yashha/percollate#10]
Some websites (e.g., https://0bin.net/paste/r0Sezz7ZPCgcYnUb#hBK4Y3oKjYlw5nk5OJXb3vzW4ddYMqMbo+CSyfbUZDa ) need special handling to get their useful html. I already have the necessary scripts to handle them, but I can’t supply the resulting html into percollate for cleaning.

**Comment by yashha** [comment]
Would be a good addition yes.
Maybe an idea would be to allow using file paths instead of urls.
A pr is would be nice. I have currently not much time but I'll look into it when I have some spare time.
